menu.js
As discussed in the issue https://github.com/LinxGem33/Arc-Menu/issues/20, this pull-request adds a _gnome-tweak-tool_ shortcut to the Arc Menu.
=> Add the shortcut 'Tweak Tool' to the Arc Menu

menu.js
As discussed in the issue https://github.com/LinxGem33/Arc-Menu/issues/22, this pull-request adds a _Trash_ shortcut to the Arc Menu.
=> Add a shortcut for opening the trash folder

Makefile
Installing the extension from source becomes tedious after a while. To avoid that in the future for other contributors, a Makefile for installing and uninstalling from source might be a good idea.
The Makefile in this pull-request allows a contributor to leverage the make command.
The command `make install` installs the extension in the directory ~/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com, whereas the command `make install` the extension removes.
=> Add a basic Makefile for installing/uninstalling the extension from source

extension.js, helper.js, prefs.js, schemas/org.gnome.shell.extensions.arc-menu.gschema.xml
This PQ implements the menu-position-feature as mentioned in: https://github.com/LinxGem33/Arc-Menu/issues/41. It also fixes the bug described in https://github.com/LinxGem33/Arc-Menu/issues/38.
This commit introduces the following changes:
* add a Menu Button Manager class that helps us to disable, enable,
and manage the position of the menu button
* update the schema file to include menu position
* update the prefs.js so that the user can specify the menu position: Left, Right, or Center
=> Merge implemented menu-position-feature into Development-Branch

Makefile, prefs.js
I tested this PR on my virtual machines.
**Remark:** To complete this feature, a logo.png file must be added to the folder media.
**Extra remarks:** The about page retrieves the Arc-Menu metadata from the metadata.json file. Currently, there is no version number specified in metadata.json. When the version number cannot be retrieved the about page displays 'bleeding-edge' :smile:. 
This commit introduces the following changes:
* add folder media
* add a about tab page to the prefs.js file
* update the Makefile
=> Implement a basic about page

am.js, constants.js, controller.js, extension.js, helper.js, menu.js, prefs.js, schemas/org.gnome.shell.extensions.arc-menu.gschema.xml
This feature (see https://github.com/LinxGem33/Arc-Menu/issues/46) allows the user to change the menu button appearance including:
* the menu button text
* the menu button icon
* the size of the icon
* enable or disable the arrow icon beside the menu button text
Sorry that this commit is so big, but to implement the menu-button-customization feature, I had to refactor the code base. I hope these changes will help us in the future to maintain a clean code base.
Last but not least, to fully complete this commit, a *icon.svg* file for the Arc Menu Icon has to be added to the directory media.
This commit introduces the following changes:
* Move the logic for handling settings changes in controller.js, namley in the MenuSettingsController class
* Move common constants in constants.js
* …
=> Implement menu-button-customization feature.

Makefile, extension.js, po/arc-menu.pot, po/de.po, po/fr.po, po/it.po, po/pl.po, prefs.js
This pull-request setups a basic localization infrastructure for supporting multiple languages, as requested in issue https://github.com/LinxGem33/Arc-Menu/issues/5. 
The translatable strings are contained in the file `./po/arc-menu.pot`. This file can be used to generate the po translation file for a specific language. Template Po files for some languages are found in the po directory. 
Thanks to the the adapted Makefile, we can now easily build the whole project. In summary, the Makefile supports the following make commands:
* make potfile <=> Used to generate the potfile that contains all translatable strings of the Arc Meu project.
* make translations <=> When the translatable strings change this command can be used to update all po files before updating translations.
* make build <=> …
=> Setup a basic localization infrastructure

.gitignore, Makefile
This pull-request completes the previous pull-request https://github.com/LinxGem33/Arc-Menu/pull/53 :smile:.
In short, this commit introduces the following changes:
* Makefile: adapt Makefile to compile po files to mo files
* .gitignore: adapt .gitignore to ignore build files
=> Update Makefile and .gitignore

.gitignore, Makefile, extension.js, menu.js, metadata.json, prefs.js, schemas/org.gnome.shell.extensions.arc-menu.gschema.xml
To make the code base localization ready, this commit introduces the following changes:
* .gitignore: update .gitignore so that it ignores backup files such as de.po~
* metadata.json: set gettext-domain to "arc-menu"
* schema file: set gettext-domain to "arc-menu"
* Makefile: update Makefile so it does not copy the po directory to the build directory
* prefs.js: make it localization ready
* extension.js: make it localization ready
* menu.js: fix missing strings for translation
Example of using the Italian language as the system language:
PS: JavaScript is PITA! I miss strongly and statically typed programming languages like JAVA!
=> Make the code base localization ready

Makefile
Fix Makefile so that it always rebuilds the arc-menu.pot file. 
In order to rebuild all language files on every 'make build', the  arc-menu.pot file has always to be rebuilt. 
Thus, we use the FORCE mechanism of make: https://stackoverflow.com/questions/7643838/how-to-force-make-to-always-rebuild-a-file
=> Fix Makefile: rebuild always the arc-menu.pot file

menu.js
This commit partially reverts https://github.com/LinxGem33/Arc-Menu/commit/f0f53c0f217e5a3a1e66ba1bea4943aa164473c2
Before: http://i.imgur.com/Js0LVGm.png
After: http://i.imgur.com/xgbAceA.png
=> menu: use system localization for folders

README.md
@LinxGem33 
I hope it is okay if we simplify or shorten the README.md. What do think about this proposal?
For extra information about contributing and creating translations, I think we should use the Github Wiki as documentation platform. In general, I assume that GNU/Linux/Gnome 3 enthusiasts that visit the Github repository are only interested how they can install/uninstall the extension from source.
This pull-request introduces the following changes:
* edit section Manual Installation
* edit section Bugs
* remove section Advanced Installation
=> Simplify the README.md

Makefile, README.md
@LinxGem33 
This will be my last pull-request for today :smile:.
I just found out how we can greatly simplify the Manual Installation using `make`.
Thanks to the very handy program `gnome-shell-extension-tool`, we can easily enable and disable the extension once it is installed, without restarting the GNOME Shell. 
That is pretty cool. For more details see:
https://wiki.gnome.org/Projects/GnomeShell/Extensions
This commit introduces the following changes:
* Makefile: add `make enable` command to enable the extension.
* Makefile: add `make disable` command to disable the extension.
* README.md: update the section Manual Installation
=> Makefile: Simplify the installation of the extension

controller.js
This pull-request refactors controller.js. 
It introduces the method _isActivitiesButtonPresent which checks if the Activities Button is present on the main panel. In short, it is used to check if we can add/remove the Activities Button to the main panel.
Thanks to @lestcape for the refinement of this method and the bug report.
I tested it on my virtual machines:
* Ubuntu Gnome 16.04 LTS
* Ubuntu Gnome 17.04
* Debian Stretch
* Debian Sid
* Arch Linux
=> controller.js: implement method _isActivitiesButtonPresent

controller.js, stylesheet.css
As discussed with **@LinxGem33**, we don't fix theme issues in our JS/CSS code since this would introduce workarounds and fishy code in our code base.
In a nutshell, this commit basically reverts the pull request: https://github.com/LinxGem33/Arc-Menu/pull/87
=> remove fixes for the adapta theme

menu.js
This pull-request removes dead code in menu.js (see class ApplicationsButton),
which uses some dead from the upstream GNOME apps-menu.
For more details see the bug reports on bugzilla.gnome.org:
* https://bugzilla.gnome.org/show_bug.cgi?id=785200
* https://bugzilla.gnome.org/show_bug.cgi?id=785202
=> menu.js: remove dead code

menu.js
This pull-request eliminates lot of unnecessary code in menu.js.
In short, it removes some code in the class ApplicationMenuItem. I could not figure out what the removed code was supposed to accomplish and I could not find any difference in the behaviour of the menu.
As a reference for the code elimination I used the upstream implementation of ApplicationMenuItem in the [gnome-apps extension](https://github.com/GNOME/gnome-shell-extensions/blob/master/extensions/apps-menu/extension.js) as well as the class PopupBaseMenuItem from the [gnome-shell code base](https://github.com/GNOME/gnome-shell/blob/master/js/ui/popupMenu.js).
=> menu.js: eliminate unnecessary code in class ApplicationMenuItem

menu.js
This pull-request prepares menu.js for the rename of GNOME tweak tool (see issue #101).
Moreover, it adds a guard that checks if each shortcut can be added to the menu depending if the associated command is present on the system.
=> Prepare menu.js for gnome tweaks/GNOME 3.26

prefs.js
As the title says: prefs.js: show GPL2 info text on the about page :-)
=> prefs.js: show GPL2 info text on the about page

prefs.js, prefsWidgets.js
Another refactoring pull-request :smile:.
In summary, this pull-request introduces the following changes:
* prefsWidgets.js: add the public method getTitleLabel to the class NotebookPage
* prefsWidgets.js: make the property title of the class NotebookPage private by using the prefix _
* prefsWidgets.js: override the inherited public method Gtk.Notebook.append_page in class Notebook
to avoid boilerplate code
* prefs.js: adapt the class ArcMenuPreferencesWidget to use the new internal API
=> prefjs.js & prefsWidgets.js: refactor Notebook, NotebookPage, and ArcMenuPreferencesWidget

metadata.json
In summary:
* metadata.json: reformat json
* metadata.json: add a default version of -1
* metadata.json: drop support for 3.14 and 3.16
The use of a default version of -1 is really helpful for versioning development builds with sed and git hashes.  I assume that extensions.gnome.org will always override the version number.
=> Refactor metadata.json

.jshintrc, Makefile
In short:
* Add jshint and test (for possible future tests) targets for checking the js files using jshint. 
* And also add the missing `all` target.
If you have installed jshint, you can simply run `make jshint` for checking syntax or coding style errors. You can also run `jshint somefile.js` for checking individual files.
Currently, jshint will print lot of errors since the code base is a mess regarding the JS coding style :-).
So the goal would be to reduce them to a sane amount.
=> Makefile: add jshint and test targets

controller.js
Refcator controller.js following jshint remarks:
* use dot-notation to access property
* use '!=='  instead of '!='
* fix potential "'_' is not defined" bug
* add /* falls through */ comments for jshint
=> controller.js: refactor code following jshint remarks

menu.js
In the pull-request #104, I made a stupid mistake :-/ and deleted the `_onKeyPressEvent` handler in the class ApplicationMenuItem. For this reason the key KEY_KP_Enter is currently not handled. That was probably also the reason for the merge conflict. Shame on me :disappointed:.
This commit fixes that and backports the _onKeyPressEvent handler from this commit here: https://github.com/LinxGem33/Arc-Menu/pull/103/commits/e6a198cb5c4291d0e4beb5036cc1c37536d7c63d
=> menu.js: add _onKeyPressEvent handler to ApplicationMenuItem

Makefile
This pull-request updates the Makefile as follows:
* add help target that shows some helpful information how to use the Makefile
* add support for system-wide installation
**Remark:** 
Per default the Makefile will install the extension locally (~/.local/...). If the argument INSTALL is passed the makefile will install the extension either locally or system-wide.
**Examples:**
_Install and uninstall locally:_
```
make install
make install INSTALL=local
```
```
make uninstall
make uninstall INSTALL=local
```
_Install and uninstall system-wide (needs sudo):_
```
make install INSTALL=system
```
```
make uninstall INSTALL=system
```
_Show help message:_
```
make help
```
=> Update makefile: add help target and system-wide installation support

Makefile
This pull-request makes the Makefile ready for using the Arch Linux package here:
https://github.com/lexruee/gnome-shell-extension-arc-menu-arch
The changes in short are:
* Improve versioning for zip files and manual Arc-Menu installations
* Ignore potential errors in enable/disable targets
* Update output of the help target
After this pull-request we could think about resyncing the master branch with the dev branch.
=> Update Makefile to make it easier to build a Arch package

Makefile
This pull-request updates the Makefile to make it easier for Debian packaging (at least I hope so :-)). 
The pull-request introduces the following changes to the Makefile:
* add target tgz-file to create tar.gz files
* create checksums when invoking the targets zip-file/tgz-file (MD5, SHA1, SHA256, SHA512)
=> Update Makefile to make it easier for Debian packaging

helper.js
This pull request fixes the described bug in #95. In short, I tested this fix on Fedora 26 as well as on Ubuntu 17.10.
Shame on me! The bug was just a stupid typo (see 88b72c2) that I introduced due to lack of sleep :-). Next time I'll write tests to avoid that. 
@archqob @daniel-wtd
Can you please test this pull request and report back if it solves your issue? Thanks in advance :smiley:.
=> Fix keybinding-lockscreen bug (#95)

constants.js, controller.js, helper.js, logger.js, menu.js
I tested Arc Menu on Ubuntu 17.10 and discovered the following JS warnings (see #141):
* Warning 1: Too many arguments to method Clutter.Actor.add_child: expected 1, got 2
* Warning 2: That property was defined with 'let' or 'const' inside the module.
It seems that Clutter.Actor.add_child() only expects a single argument, namely a child actor [2].
The fix for warning 1 is pretty simple, we just remove the extra argument.
And to fix warning 2, we simply use the keyword 'var' to export classes and constants to other modules.
Thus, some 'const' keywords are replaced with a 'var' keyword in the following files:
* controller.js
* helper.js
* menu.js
* constants.js
* logger.js
[1] http://paste.debian.net/983968
[2] https://developer.gnome.org/clutter/stable/ClutterActor.html#clutter-actor-add-ch …
=> GNOME-Shell 3.25/26: Fix JS warnings (#141)

Makefile, menu.js, menuWidgets.js
This pull request moves reusable menu widgets from the module menu.js to a new module called menuWidgets.js.
The basic idea of this pull request is to allow support for different menu views in the future. These different menu views can then reuse the menu widgets from the module menuWidgets.js.
=> Move reusable menu widgets from menu.js to menuWidgets.js

README.md
@LinxGem33 
I think we should simplify the README.md. For example, this pull-request replaces the manual installation instructions with a link to the [manual installation guide](https://github.com/LinxGem33/Arc-Menu/wiki/Installing-from-extensions.gnome.org#manual-installuninstall-using-make) on the great Arc-Menu Wik :smile:.
Moreover, it adds a Section Dependencies for users that could run into GNOME dependency issues in case they installed Arc-Menu on a broken GNOME Desktop, such as Ubuntu 17.10.
=> Readme.md amendments to streamline the main page

menuWidgets.js
This pull-request introduces the class SessionButton. The latter is used to refactor the existing session
buttons such as LogoutButton, SuspendButton, etc.
Moreover, this pull-request is the foundation for the session buttons' tooltip feature that I'm working on. Here is a sneak preview of the [tooltip feature](https://github.com/lexruee/Arc-Menu/tree/feature-tooltips):
=> menuWidgets.js: Refactor session buttons

menuWidgets.js
Just discovered some minor warnings in the systemd log on Ubuntu 17.10 with gnome shell 3.26.
```
Some code accessed the property 'ApplicationMenuItem' on the module 'menuWidgets'. That property 
was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct 
according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. 
The property access will work as previously for the time being, but please fix your code anyway.
```
As of GNOME 3.26 the gnome shell complains about classes that are defined using the const keyword and which are at the same time exported to other modules, like menu.js. To fix that we define all classes in menuWidgets.js using the var keyword. 
This is also what the GNOME devs did in the …
=> menuWidgets.js: Define classes using var keyword

menu.js
Hi LinxGem33, this is a small fix for #215. Seems like the menu sections are destroyed by the parent (PopupMenuBase in gnome-shell/ui/popupMenu.js), so no need to destroy them explicitly. Cheers!
=> Prevent double destruction of the menu sections when disabling the extension

menu.js
Hi LinxGem33, I could reproduce the warnings as mentioned in #209, although my system doesn't freeze. Seems like, coming back from the lock screen, dash to panel is enabled before arc-menu and sends a height notification that arc-menu listens to (while not yet enabled), and it causes the issue. Disconnecting the signal on disable fixes it on my end. Cheers!
=> Disconnect height notification signal on extension disable

menuWidgets.js
Changing the default avatar image to be symbolic makes the icon more consistent with the rest of the right pane of the menu.
=> Made default user avatar image symbolic

menu.js
adds a shortcut to the gnome terminal on the menu
=> Add terminal shortcut to menu.js
