LinxGem33/Arc-Menu

menu.js, stylesheet.css
Fixes https://github.com/LinxGem33/Arc-Menu/issues/6
=> menu-style-fix

menu.js
Asynchronously set an icon and handle errors.
setIconAsync takes an icon which you want to change, a Gio.File representing an image file(local or remote) that may or may not exist, and a fallback icon name to use if the file does not exist. It then asynchronously loads the contents into a gicon if successful otherwise it sets the icon to the fallback icon name.
This removes the need for blocking I/O when loading images from a file.
=> Async Icons

po/it.po
=> Italian Translation

README.md, po/ru.po, po/uk_UA.po
This pull request adds initial support for Ukrainian and Russian languages, fixes some misprints and improves the general look and feel of README document.
Overall, this PR introduces the following changes:
- README.md: misprint corrections, updated list of languages, table markup cheatsheet
- po: added files for two new languages
=> Added Ukrainian and Russian translations, minor README.md corrections

menu.js
This pull request refactors some code in menu.js.
In a nutshell, it refactors the class MenuButtonWidget and removes an unused constant named availableIconSizes. For more details, see the commit messages.
=> Refactor menu.js

controller.js, helper.js
This pull-request fixes the issue https://github.com/LinxGem33/Arc-Menu/issues/97.
=> fix: keep disabled hot corner disabled on new session

menu.js
This pull-request fixes issue #77.
In short, this pull-request fixes the following issues:
* pressing the ENTER key does not add anymore a special char to the search box
* The enter key performs the same action as the return key
=> menu.js: fix #77

prefsWidgets.js
This pull-request just refactors the class IconButton:
* use misc.params to parse constructor params
* remove unnecessary map {} object
=> prefsWidgets.js: refactor class IconButton

prefs.js
Zut, I deleted the wrong branch on my repo. Anyways, this is just a duplicate of https://github.com/LinxGem33/Arc-Menu/pull/120. I need to clean up my Arc-Menu repo :smile:.
-------
These are just simple refactorings that I made with the help of jshint, which is really a nice linter :-). I highly recommend to use it during your programming sessions.
For details of the changes see each commit log.
@LinxGem33  if this pull-request conflicts with your implemented features, we can postpone it to another pull-request, since these are not really important :smile:.
=> Refactor prefs.js

po/hi_IN.po
Some words are transliterated because Hindi doesn't have enough relevant vocabulary.
=> Hindi translations for Arc-Menu

menu.js
@LinxGem33 
To keeps things simple, I decided to make a pull request with this simple fix for #150.
Other changes regarding the search box feature deserve their own pull request :-).
@archqob 
Can you please test this pull request and report back if it solves your issue? Thanks in advance :smiley:.
=> menu.js: remove space key support to launch apps

menu.js
This pull request refactors and improves some code parts in menu.js. Overall, the pull request improves code readability :smile:.
=> Refactor some code parts in menu.js

stylesheet.css
This pull request should fix the menu resize bug #153.
@archqob Can you please test again another pull-request? Thanks in advance :smile:.
=> stylesheet.css: set max-width for ST.Entry to fix menu resize bug

prefs.js
As the title says: Comment temporarily the general settings page :-).
=> prefs.js: Comment temporarily the general settings page

menu.js, menuWidgets.js
This is the final pull-request on my part for the release v15. :smile:
The commits in the pull-request reimplement the search box and should fix input issues such as #131.
=> Reimplement the search box

po/ar.po
@@ -0,0 +1,210 @@
+# SOME DESCRIPTIVE TITLE.
+# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
+# This file is distributed under the same license as the Arc Menu package.
+# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
+#
+#, fuzzy
+msgid ""
+msgstr ""
+"Project-Id-Version: Arc Menu\n"
+"Report-Msgid-Bugs-To: \n"
+"POT-Creation-Date: 2017-07-09 16:20+0200\n"
+"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
+"Last-Translator: Madaramost <madaramost@gmail.com>\n"
+"Language-Team: LANGUAGE <LL@li.org>\n"
+"Language: ar\n"
+"MIME-Version: 1.0\n"
+"Content-Type: text/plain; charset=UTF-8\n"
+"Content-Transfer-Encoding: 8bit\n"
+
+#: prefs.js:76
+msgid "Behaviour"
+msgstr "الأداء"
+
+#: prefs.js:85
+msgid "Disable activities hot corner"
+msgstr "تعطيل نوافذ الزوايا"
+
+#: prefs.js:107
+msgid "Set menu …
=> add-arabic-translation

extension.js
This is a small DnD bug fix. extension.js needs to be adjusted to the recent
refactorings (menuWidgets.js) so the app launcher DnD code works again.
=> extension.js: DnD bug fix

po/es.po
New translation file in Spanish.
=> new file: es.po

po/sr.po, po/sr@latin.po
=> Add Serbian translation (sr and sr@latin)

menuWidgets.js, prefs.js, schemas/org.gnome.shell.extensions.arc-menu.gschema.xml, stylesheet.css
Tooltip session button feature.
=> Tooltip session button feature 
